name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish -c Release -o published --no-restore
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: published/wwwroot
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1